import type {
  CreateUserInput,
  Paginated,
  UpdateUserInput,
  UserListQuery,
  UserRecord,
} from "@c26/contracts";
import { changedFields, recordAudit, type AuditActor } from "../../kernel/audit.ts";
import { getPrisma, withTransaction, type Tx } from "../../kernel/db.ts";
import { AppError } from "../../kernel/envelope/index.ts";
import { publishEvent } from "../../kernel/outbox.ts";
import { generateTemporaryPassword, hashPassword } from "../../kernel/security/password.ts";
import { revokeAllSessions } from "../auth/index.ts";

/**
 * User management (PLAN/04 §5) — closes D-12.
 *
 * The legacy system had add and delete and nothing else. What the four guards
 * below protect against is specific and severe: `uq_users_username_active` makes
 * a username reusable after deletion, so without them one click could lock
 * everybody out of the system permanently.
 */

/**
 * Guard 2, and the reason it runs inside the transaction rather than before it:
 * two admins deleting each other simultaneously would each see one other active
 * admin and both succeed.
 */
async function assertNotLastActiveAdmin(tx: Tx, targetUserId: bigint): Promise<void> {
  const remaining = await tx.user.count({
    where: {
      role: "admin",
      isActive: true,
      deletedAt: null,
      NOT: { id: targetUserId },
    },
  });

  if (remaining === 0) {
    throw new AppError("VALIDATION_ERROR", {
      fieldErrors: [
        {
          field: "root",
          code: "NOT_ALLOWED",
          message:
            "Ini admin aktif terakhir. Tambahkan admin lain terlebih dahulu sebelum mengubah atau menghapus akun ini.",
        },
      ],
    });
  }
}

/** Guard 1: nobody deletes or deactivates themselves. */
function assertNotSelf(actorId: bigint, targetUserId: bigint, action: string): void {
  if (actorId === targetUserId) {
    throw new AppError("VALIDATION_ERROR", {
      fieldErrors: [
        { field: "root", code: "NOT_ALLOWED", message: `Anda tidak dapat ${action} akun Anda sendiri.` },
      ],
    });
  }
}

function toRecord(user: {
  id: bigint;
  username: string;
  displayName: string;
  role: UserRecord["role"];
  email: string | null;
  phone: string | null;
  isActive: boolean;
  mustChangePassword: boolean;
  lastLoginAt: Date | null;
  createdAt: Date;
  mfa: { confirmedAt: Date | null } | null;
  regions: {
    provinceId: bigint | null;
    cityId: bigint | null;
    province: { name: string } | null;
    city: { name: string } | null;
  }[];
}): UserRecord {
  return {
    id: Number(user.id),
    username: user.username,
    displayName: user.displayName,
    role: user.role,
    email: user.email,
    phone: user.phone,
    isActive: user.isActive,
    mustChangePassword: user.mustChangePassword,
    mfaEnrolled: user.mfa !== null && user.mfa.confirmedAt !== null,
    lastLoginAt: user.lastLoginAt?.toISOString() ?? null,
    createdAt: user.createdAt.toISOString(),
    regions: user.regions.map((region) => ({
      provinceId: region.provinceId === null ? null : Number(region.provinceId),
      cityId: region.cityId === null ? null : Number(region.cityId),
      name: region.city?.name ?? region.province?.name ?? "",
    })),
  };
}

const USER_INCLUDE = {
  mfa: { select: { confirmedAt: true } },
  regions: { include: { province: { select: { name: true } }, city: { select: { name: true } } } },
} as const;

export async function listUsers(query: UserListQuery): Promise<Paginated<UserRecord>> {
  const prisma = getPrisma();
  const where = {
    deletedAt: null,
    ...(query.role !== undefined ? { role: query.role } : {}),
    ...(query.isActive !== undefined ? { isActive: query.isActive } : {}),
    ...(query.q !== undefined && query.q !== ""
      ? {
          OR: [
            { username: { contains: query.q, mode: "insensitive" as const } },
            { displayName: { contains: query.q, mode: "insensitive" as const } },
          ],
        }
      : {}),
  };

  const [items, total] = await Promise.all([
    prisma.user.findMany({
      where,
      include: USER_INCLUDE,
      orderBy: [{ isActive: "desc" }, { displayName: "asc" }],
      skip: (query.page - 1) * query.perPage,
      take: query.perPage,
    }),
    prisma.user.count({ where }),
  ]);

  return {
    items: items.map(toRecord),
    page: query.page,
    perPage: query.perPage,
    total,
    totalPages: Math.max(1, Math.ceil(total / query.perPage)),
  };
}

export interface CreatedUser {
  user: UserRecord;
  temporaryPassword: string;
}

export async function createUser(
  actor: AuditActor & { id: bigint },
  input: CreateUserInput,
): Promise<CreatedUser> {
  // Generated by the system, single use, must be changed on first login
  // (PLAN/04 §4.1). No password ever arrives from a form.
  const temporaryPassword = generateTemporaryPassword();
  const passwordHash = await hashPassword(temporaryPassword);

  const created = await withTransaction(async (tx) => {
    const user = await tx.user.create({
      data: {
        username: input.username,
        displayName: input.displayName,
        role: input.role,
        email: input.email ?? null,
        phone: input.phone ?? null,
        passwordHash,
        mustChangePassword: true,
        createdById: actor.id,
        regions: {
          create: input.regions.map((region) => ({
            provinceId: region.provinceId ?? null,
            cityId: region.cityId ?? null,
          })),
        },
      },
      include: USER_INCLUDE,
    });

    await recordAudit(tx, actor, {
      action: "user.created",
      entity: "user",
      entityId: user.id,
      after: {
        username: user.username,
        displayName: user.displayName,
        role: user.role,
        regionCount: input.regions.length,
      },
    });

    return user;
  });

  return { user: toRecord(created), temporaryPassword };
}

export async function updateUser(
  actor: AuditActor & { id: bigint },
  targetUserId: bigint,
  input: UpdateUserInput,
): Promise<UserRecord> {
  return withTransaction(async (tx) => {
    const before = await tx.user.findFirst({
      where: { id: targetUserId, deletedAt: null },
      include: USER_INCLUDE,
    });
    if (before === null) throw new AppError("NOT_FOUND");

    const losesAdmin =
      (input.role !== undefined && input.role !== "admin" && before.role === "admin") ||
      (input.isActive === false && before.role === "admin");

    if (losesAdmin) {
      assertNotSelf(actor.id, targetUserId, "menurunkan peran atau menonaktifkan");
      await assertNotLastActiveAdmin(tx, targetUserId);
    }
    if (input.isActive === false) {
      assertNotSelf(actor.id, targetUserId, "menonaktifkan");
    }

    const updated = await tx.user.update({
      where: { id: targetUserId },
      data: {
        displayName: input.displayName,
        role: input.role,
        isActive: input.isActive,
        email: input.email,
        phone: input.phone,
        ...(input.regions !== undefined
          ? {
              regions: {
                deleteMany: {},
                create: input.regions.map((region) => ({
                  provinceId: region.provinceId ?? null,
                  cityId: region.cityId ?? null,
                })),
              },
            }
          : {}),
      },
      include: USER_INCLUDE,
    });

    const diff = changedFields(
      {
        displayName: before.displayName,
        role: before.role,
        isActive: before.isActive,
        email: before.email,
        phone: before.phone,
      },
      {
        displayName: updated.displayName,
        role: updated.role,
        isActive: updated.isActive,
        email: updated.email,
        phone: updated.phone,
      },
    );

    const roleChanged = before.role !== updated.role;

    await recordAudit(tx, actor, {
      action: roleChanged ? "user.role_changed" : "user.updated",
      entity: "user",
      entityId: targetUserId,
      before: diff.before,
      after: diff.after,
    });

    // Guard 3: a role downgrade takes effect now, not when the old session
    // happens to expire. This is the requirement that ruled out JWTs entirely
    // (PLAN/13 §1.1).
    if (roleChanged || input.isActive === false) {
      const revoked = await revokeAllSessions(tx, targetUserId);
      if (revoked > 0) {
        await recordAudit(tx, actor, {
          action: "auth.sessions_revoked",
          entity: "user",
          entityId: targetUserId,
          after: { revokedSessions: revoked, reason: roleChanged ? "role_changed" : "deactivated" },
        });
      }
    }

    return toRecord(updated);
  });
}

export async function resetPassword(
  actor: AuditActor & { id: bigint },
  targetUserId: bigint,
): Promise<{ temporaryPassword: string; revokedSessions: number }> {
  const temporaryPassword = generateTemporaryPassword();
  const passwordHash = await hashPassword(temporaryPassword);

  const revokedSessions = await withTransaction(async (tx) => {
    const target = await tx.user.findFirst({ where: { id: targetUserId, deletedAt: null } });
    if (target === null) throw new AppError("NOT_FOUND");

    await tx.user.update({
      where: { id: targetUserId },
      data: { passwordHash, mustChangePassword: true },
    });

    const revoked = await revokeAllSessions(tx, targetUserId);

    await recordAudit(tx, actor, {
      action: "user.password_reset",
      entity: "user",
      entityId: targetUserId,
      after: { revokedSessions: revoked },
    });

    await publishEvent(
      tx,
      { id: actor.id, requestId: actor.requestId },
      {
        type: "user.password_reset",
        aggregateId: targetUserId,
        payload: { userId: targetUserId.toString() },
      },
    );

    return revoked;
  });

  return { temporaryPassword, revokedSessions };
}

/**
 * Soft delete only (PLAN/04 §5).
 *
 * The inspections this person created stay, and keep referring to them. Erasing
 * the author of a QC decision would hollow out the audit trail that D-15 exists
 * to build.
 */
export async function deleteUser(
  actor: AuditActor & { id: bigint },
  targetUserId: bigint,
  confirmUsername: string,
): Promise<void> {
  await withTransaction(async (tx) => {
    const target = await tx.user.findFirst({ where: { id: targetUserId, deletedAt: null } });
    if (target === null) throw new AppError("NOT_FOUND");

    // Guard 4: retyping the username, checked server-side too. A browser
    // confirm() is forbidden (D-08) and would not be verifiable anyway.
    if (target.username.toLowerCase() !== confirmUsername.trim().toLowerCase()) {
      throw new AppError("VALIDATION_ERROR", {
        fieldErrors: [
          {
            field: "confirmUsername",
            code: "NOT_ALLOWED",
            message: "User ID yang diketik tidak cocok.",
          },
        ],
      });
    }

    assertNotSelf(actor.id, targetUserId, "menghapus");
    if (target.role === "admin") await assertNotLastActiveAdmin(tx, targetUserId);

    await tx.user.update({
      where: { id: targetUserId },
      data: { deletedAt: new Date(), isActive: false },
    });
    await revokeAllSessions(tx, targetUserId);

    await recordAudit(tx, actor, {
      action: "user.deleted",
      entity: "user",
      entityId: targetUserId,
      before: { username: target.username, role: target.role, isActive: target.isActive },
      after: { deleted: true },
    });
  });
}

export async function getUser(targetUserId: bigint): Promise<UserRecord> {
  const user = await getPrisma().user.findFirst({
    where: { id: targetUserId, deletedAt: null },
    include: USER_INCLUDE,
  });
  if (user === null) throw new AppError("NOT_FOUND");
  return toRecord(user);
}
