import { useEffect, useState, type ChangeEvent, type ReactNode } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Link, useParams } from "react-router-dom";
import {
  MAX_PHOTOS_PER_INSPECTION,
  MAX_PHOTOS_PER_SLOT,
  PHOTO_SLOT_LABELS,
  type InspectionDetail,
  type PhotoRecord,
  type QcReviewRecord,
} from "@c26/contracts";
import { api } from "../../lib/api-client.ts";
import { formatDateTime } from "../../lib/format.ts";
import { useSession } from "../../lib/session.tsx";
import {
  enqueuePhoto,
  removeQueueItems,
  retryFailedIn,
  subscribeToQueue,
} from "../../lib/photo/upload-queue.ts";
import type { QueueItem } from "../../lib/photo/queue-store.ts";
import { Banner, ErrorBanner, StatusBadge, useToast } from "../../components/ui/feedback.tsx";
import { Button, Card, PageHeader, Spinner } from "../../components/ui/primitives.tsx";
import { ChangeHistory } from "./change-history.tsx";

/**
 * One inspection: its data, its photo slots, and its QC history.
 *
 * The photo slots are generated by the axle engine, so their names match the
 * specification cards and the storage keys exactly — one source, three consumers
 * (PLAN/03 §1). That consistency is what lets a photograph and a specification
 * still be paired months later.
 */
export function InspectionDetailPage(): ReactNode {
  const { sn = "" } = useParams();
  const queryClient = useQueryClient();
  const toast = useToast();
  const { can } = useSession();
  const [queue, setQueue] = useState<QueueItem[]>([]);
  const [error, setError] = useState<unknown>(null);

  useEffect(() => subscribeToQueue(setQueue), []);

  const detail = useQuery({
    queryKey: ["inspection", sn],
    queryFn: () => api.get<InspectionDetail>(`/api/inspections/${sn}`),
  });

  const photos = useQuery({
    queryKey: ["inspection-photos", sn],
    queryFn: () => api.get<PhotoRecord[]>(`/api/inspections/${sn}/photos`),
  });

  const reviews = useQuery({
    queryKey: ["inspection-reviews", sn],
    queryFn: () => api.get<QcReviewRecord[]>(`/api/qc/${sn}/reviews`),
  });

  const submit = useMutation({
    mutationFn: () => api.post<{ status: string }>(`/api/inspections/${sn}/submit`),
    onSuccess: async () => {
      toast.push({ tone: "success", message: "Pengajuan dikirim ke antrean QC." });
      await queryClient.invalidateQueries({ queryKey: ["inspection", sn] });
    },
    onError: setError,
  });

   if (detail.isLoading) {
     return (
       <div className="flex justify-center py-16 text-muted">
         <Spinner className="h-6 w-6" />
       </div>
     );
   }

  if (detail.error !== null) return <ErrorBanner error={detail.error} />;
  if (detail.data === undefined) return null;

  const inspection = detail.data;
  const queueForThis = queue.filter((item) => item.serialNumber === sn);
  const editable = inspection.status === "draft" || inspection.status === "needs_revision";
  const photosBySlot = photos.data ?? [];

  // The 30-per-inspection cap in `PLAN/06` §6 binds across every slot, so a slot
  // cannot decide it alone: on a six-position vehicle the ceiling is reached
  // long before any one slot sees its tenth photograph.
  const uploadedInInspection = photosBySlot.length;

   return (
     <div className="space-y-4">
      <PageHeader
        title={inspection.serialNumber}
        description={`${inspection.plateDisplay} · ${inspection.cityName}, ${inspection.provinceName}`}
        breadcrumbs={[{ label: "Pengajuan", to: "/inspections" }, { label: inspection.serialNumber }]}
        renderCrumbLink={(crumb) => (
          <Link to={crumb.to ?? "#"} className="text-accent-text hover:underline">
            {crumb.label}
          </Link>
        )}
        actions={<StatusBadge status={inspection.status} />}
      />

      {error !== null ? <ErrorBanner error={error} onDismiss={() => setError(null)} /> : null}

      {/* The revision reason, front and centre. D-11 is only half solved if the
          supplier learns they were rejected but not what to fix. */}
      {inspection.status === "needs_revision" && inspection.latestQcNotes !== null ? (
        <Banner tone="warning" title="Perlu diperbaiki">
          {inspection.latestQcNotes}
        </Banner>
      ) : null}

      {inspection.status === "dropped_qc" && inspection.latestQcNotes !== null ? (
        <Banner tone="error" title="Pengajuan ditolak">
          <p>{inspection.latestQcNotes}</p>
          <p className="mt-1 text-xs">
            Pengajuan yang ditolak bersifat final. Kalau data perlu diperbaiki, buat pemeriksaan baru
            untuk kendaraan ini.
          </p>
        </Banner>
      ) : null}

      <Card title="Data Kendaraan">
        <dl className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">
          <Detail label="Plat Nomor" value={inspection.plateDisplay} />
          <Detail label="Nomor Rangka" value={inspection.chassisNumber ?? "—"} />
          <Detail label="Kategori" value={inspection.category} />
          <Detail label="Segmen" value={`${inspection.segment} · ${inspection.subSegment}`} />
          <Detail label="Merk" value={inspection.vehicleBrandName ?? "—"} />
          <Detail label="Jenis Muatan" value={inspection.cargoType} />
          <Detail label="Jumlah Poros" value={`${inspection.axleCount} poros`} />
          <Detail label="Total Ban Terhitung" value={`${inspection.totalTires} ban`} />
          <Detail label="Dikirim" value={formatDateTime(inspection.submittedAt)} />
        </dl>
      </Card>

      <Card
        title="Foto Umum"
        description={`Maksimal ${MAX_PHOTOS_PER_SLOT} foto per slot, ${MAX_PHOTOS_PER_INSPECTION} foto per pengajuan.`}
      >
        <div className="grid gap-4 sm:grid-cols-2">
          {inspection.generalPhotos.map((general) => (
            <PhotoSlot
              key={general.slot}
              serialNumber={sn}
              label={PHOTO_SLOT_LABELS[general.slot as keyof typeof PHOTO_SLOT_LABELS]}
              slot={general.slot as "front_rear" | "side"}
              tirePositionId={null}
              editable={editable}
              photos={photosBySlot.filter((photo) => photo.slot === general.slot)}
              queued={queueForThis.filter((item) => item.slot === general.slot)}
              uploadedInInspection={uploadedInInspection}
              onError={setError}
            />
          ))}
        </div>
      </Card>

      <Card
        title="Foto per Posisi Ban"
        description="Nama posisi diturunkan sistem dari konfigurasi poros — tidak diketik manual."
      >
        <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
          {inspection.tirePositions.map((position) => (
            <PhotoSlot
              key={position.id}
              serialNumber={sn}
              label={position.positionLabel}
              sublabel={position.positionCode}
              slot="tire_position"
              tirePositionId={position.id}
              editable={editable}
              photos={photosBySlot.filter((photo) => photo.tirePositionId === position.id)}
              queued={queueForThis.filter((item) => item.tirePositionId === position.id)}
              uploadedInInspection={uploadedInInspection}
              onError={setError}
            />
          ))}
        </div>
      </Card>

      {editable ? (
        <Card title="Kirim Pengajuan">
          {/* PLAN/06 §2: submission waits for the photos. The alternative —
              submit now, photos follow — puts half-finished inspections in the
              QC queue with no evidence, and an admin cannot tell those apart
              from ones that genuinely have none. */}
          {inspection.submitBlockedReason !== null ? (
            <Banner tone="warning">{inspection.submitBlockedReason}</Banner>
          ) : (
            <p className="text-sm text-muted">
              Semua foto sudah terunggah. Pengajuan siap dikirim ke antrean QC.
            </p>
          )}

          <Button
            className="mt-3"
            disabled={!inspection.canSubmit}
            loading={submit.isPending}
            loadingText="Mengirim…"
            onClick={() => submit.mutate()}
          >
            {inspection.status === "needs_revision" ? "Kirim Ulang" : "Kirim Pengajuan"}
          </Button>
        </Card>
      ) : null}

      {inspection.status === "passed_qc" && can("tirespec.write") ? (
       <Card title="Spesifikasi Ban">
           <p className="text-sm text-muted">
             Terisi {inspection.specProgress.filled} dari {inspection.specProgress.total} posisi.
           </p>
          <Link to={`/inspections/${sn}/tire-specs`}>
            <Button className="mt-3">Isi Spesifikasi Ban</Button>
          </Link>
        </Card>
      ) : null}

       <Card title="Riwayat Quality Control">
         {reviews.data === undefined || reviews.data.length === 0 ? (
           <p className="text-sm text-muted">Belum ada keputusan QC.</p>
         ) : (
          <ol className="space-y-3">
            {/* A history table, not a status column. The legacy system kept
                `Nama Admin QC` on the record, so a second decision erased the
                first and nobody could tell there had been one (PLAN/02 §9). */}
             {reviews.data.map((review) => (
               <li key={review.id} className="rounded-md border border-line p-3">
                 <div className="flex flex-wrap items-center justify-between gap-2">
                   <p className="text-sm font-medium text-body">
                     {review.statusBefore} → {review.statusAfter}
                   </p>
                   <p className="text-xs text-muted">{formatDateTime(review.reviewedAt)}</p>
                 </div>
                 <p className="mt-0.5 text-xs text-muted">oleh {review.reviewerName}</p>
                 {review.notes !== null ? (
                   <p className="mt-2 text-sm text-body">{review.notes}</p>
                 ) : null}
                 {review.comments.length > 0 ? (
                   <ul className="mt-2 space-y-1">
                     {review.comments.map((comment) => (
                       <li key={comment.id} className="text-sm text-muted">
                         <span className="font-medium">
                           {comment.tirePositionLabel ?? "Foto"}:
                         </span>{" "}
                         {comment.body}
                       </li>
                     ))}
                   </ul>
                 ) : null}
               </li>
             ))}
          </ol>
        )}
      </Card>

      <ChangeHistory inspectionId={inspection.id} />
    </div>
  );
}

function Detail({ label, value }: { label: string; value: string }): ReactNode {
   return (
     <div>
       <dt className="text-xs uppercase tracking-wide text-muted">{label}</dt>
       <dd className="mt-0.5 text-sm text-body">{value}</dd>
     </div>
   );
 }

interface PhotoSlotProps {
  serialNumber: string;
  label: string;
  sublabel?: string;
  slot: "front_rear" | "side" | "tire_position";
  tirePositionId: number | null;
  editable: boolean;
  photos: PhotoRecord[];
  queued: QueueItem[];
  /** Photographs the server holds across the whole inspection, for the 30 cap. */
  uploadedInInspection: number;
  onError: (error: unknown) => void;
}

function PhotoSlot({
  serialNumber,
  label,
  sublabel,
  slot,
  tirePositionId,
  editable,
  photos,
  queued,
  uploadedInInspection,
  onError,
}: PhotoSlotProps): ReactNode {
  const [busy, setBusy] = useState(false);
  const total = photos.length + queued.length;

  const failed = queued.filter((item) => item.status === "failed");
  // One message, not one per photograph: ten copies of "Maksimal 10 foto per
  // slot" tells the reader nothing the first copy did not.
  const failureReason = failed.find((item) => item.lastError !== null)?.lastError ?? null;

  const onFilesSelected = async (event: ChangeEvent<HTMLInputElement>): Promise<void> => {
    const files = Array.from(event.target.files ?? []);
    event.target.value = "";
    if (files.length === 0) return;

    setBusy(true);
    try {
      for (const file of files) {
        // Compression, checksum, and queueing all happen on the device. The
        // photo is safe in IndexedDB before any network call is attempted —
        // which is the point of the whole offline design (PLAN/06 §4).
        //
        // The counts go with it so `enqueuePhoto` can refuse one that would
        // break V-13 before it is compressed and stored. Selecting twelve files
        // at once used to queue all twelve; the server then rejected two of them
        // permanently, and they stayed on the screen as failures.
        await enqueuePhoto({
          serialNumber,
          tirePositionId,
          positionLabel: label,
          slot,
          file,
          uploadedInSlot: photos.length,
          uploadedInInspection,
        });
      }
    } catch (error) {
      onError(error);
    } finally {
      setBusy(false);
    }
  };

   return (
     <div className="rounded-md border border-line p-3">
       <div className="flex items-baseline justify-between gap-2">
         <div className="min-w-0">
           <p className="truncate text-sm font-medium text-body">{label}</p>
           {sublabel !== undefined ? (
             <p className="font-mono text-xs text-subtle">{sublabel}</p>
           ) : null}
         </div>
         {/* Not red at zero any more. A position with no photograph no longer
             blocks submission — no document ever asked it to — so colouring it
             as an error was telling the supplier about a problem that does not
             exist. */}
         <span className="text-xs text-muted">
           {total}/{MAX_PHOTOS_PER_SLOT}
         </span>
       </div>

       {photos.length > 0 || queued.length > 0 ? (
         <ul className="mt-2 flex flex-wrap gap-2">
           {photos.map((photo) => (
             <li key={photo.id}>
               <img
                 src={photo.thumbnailUrl ?? photo.url}
                 alt={photo.tirePositionLabel ?? label}
                 loading="lazy"
                 className="h-16 w-16 rounded border border-line object-cover"
               />
             </li>
           ))}
           {queued.map((item) => (
             <li
               key={item.id}
               className={
                 item.status === "failed"
                   ? "flex h-16 w-16 flex-col items-center justify-center rounded border border-dashed border-danger-line bg-danger-soft text-center"
                   : "flex h-16 w-16 flex-col items-center justify-center rounded border border-dashed border-warning-line bg-warning-soft text-center"
               }
               title={item.lastError ?? "Menunggu sinyal"}
             >
               <span
                 className={
                   item.status === "failed"
                     ? "text-[10px] font-medium text-danger-text"
                     : "text-[10px] font-medium text-warning-text"
                 }
               >
                 {item.status === "failed" ? "Gagal" : "Menunggu"}
               </span>
               <span
                 className={
                   item.status === "failed" ? "text-[10px] text-danger-text" : "text-[10px] text-warning-text"
                 }
               >
                 unggah
               </span>
             </li>
           ))}
         </ul>
       ) : (
         <p className="mt-2 text-xs text-subtle">Belum ada foto.</p>
       )}

      {/*
        A way out of a failed upload, on the screen where the failure appears.
        Before this the tiles were dead: no retry, no removal, and once the
        failures pushed the count past the cap the file input disappeared too,
        so the slot could not be corrected at all.

        Per-item control stays on the queue screen. Here the useful unit is the
        slot — when one photograph in a slot fails, usually all of them have,
        for the same reason.
      */}
      {failed.length > 0 ? (
        <div className="mt-2 rounded border border-danger-line bg-danger-soft p-2">
          <p className="text-xs text-danger-text">
            {failed.length} foto gagal diunggah
            {failureReason === null ? "." : `: ${failureReason}`}
          </p>
          <div className="mt-2 flex flex-wrap gap-2">
            <Button
              size="sm"
              variant="secondary"
              onClick={() => void retryFailedIn(failed.map((item) => item.id))}
            >
              Coba Lagi
            </Button>
            <Button
              size="sm"
              variant="danger"
              onClick={() => void removeQueueItems(failed.map((item) => item.id))}
            >
              Buang yang Gagal
            </Button>
          </div>
        </div>
      ) : null}

      {editable && total < MAX_PHOTOS_PER_SLOT ? (
        <label className="mt-3 block">
          <span className="sr-only">Ambil foto {label}</span>
          <input
            type="file"
            accept="image/*"
            // `capture` opens the camera directly on a phone, which is where
            // this is used.
            capture="environment"
            multiple
            disabled={busy}
            onChange={(event) => void onFilesSelected(event)}
            className="block w-full text-xs file:mr-2 file:min-h-9 file:rounded file:border-0 file:bg-accent file:px-3 file:text-on-accent"
          />
        </label>
      ) : editable ? (
        // The input is gone because the slot is full. Saying so is the
        // difference between a limit and a broken screen — especially when the
        // count is full of failures the supplier can now clear above.
        <p className="mt-3 text-xs text-muted">
          Slot ini sudah penuh ({MAX_PHOTOS_PER_SLOT} foto). Buang foto yang gagal atau hapus
          dari antrean unggah untuk menambah lagi.
        </p>
      ) : null}

       {busy ? <p className="mt-2 text-xs text-muted">Mengompresi foto…</p> : null}
    </div>
  );
}
