/**
 * GENERATED by `scripts/fetch-images.ts`. Do not edit.
 *
 * Attribution read from each file's own metadata on Wikimedia Commons.
 * CC BY and CC BY-SA both require the author, the licence, and a link back,
 * so these are a condition of use, not decoration.
 */

export interface PhotoCredit {
  readonly author: string;
  readonly license: string;
  /** Empty for public domain, which has no deed to link. */
  readonly licenseUrl: string;
  readonly sourceUrl: string;
}

export const PHOTO_CREDITS = {
  "undefined": {
    author: "Lee Coursey from Decatur, GA",
    license: "CC BY 2.0",
    licenseUrl: "https://creativecommons.org/licenses/by/2.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Texture_-_tire_tread_(30784753).jpg",
  },
  "undefined": {
    author: "Biso",
    license: "CC BY 3.0",
    licenseUrl: "https://creativecommons.org/licenses/by/3.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Truck_tires.JPG",
  },
  "undefined": {
    author: "THE STEPHEN J MASON PHOTOGRAPHY COLLECTION",
    license: "CC BY-SA 2.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/2.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:AKDP_BUS_PROBOLINGGO_JAVA_INDONESIA_APRIL_2010.jpg",
  },
} as const satisfies Record<string, PhotoCredit>;
