/**
 * GENERATED by `scripts/process-images.ts`. Do not edit.
 *
 * Which renditions exist for each photograph. `Photo` builds its `srcset`
 * from this rather than from a guess, so it never offers a file that was not
 * produced — the tread macro stops at 1280 because its source does.
 */

export interface PhotoManifest {
  readonly widths: readonly number[];
  /** width / height */
  readonly aspect: number;
}

export const PHOTOS = {
  "tire-tread": { widths: [640, 1280], aspect: 0.750000 },
  "tire-stack": { widths: [640, 1280, 1920], aspect: 0.750000 },
  "depot": { widths: [640, 1280, 1920], aspect: 1.777778 },
} as const satisfies Record<string, PhotoManifest>;

export type PhotoName = keyof typeof PHOTOS;
