/**
 * GENERATED by `scripts/fetch-images.ts`. Do not edit.
 *
 * Attribution read from each file's own metadata on Wikimedia Commons.
 * CC BY and CC BY-SA both require the author, the licence, and a link back,
 * so these are a condition of use, not decoration.
 */

export interface PhotoCredit {
  readonly author: string;
  readonly license: string;
  /** Empty for public domain, which has no deed to link. */
  readonly licenseUrl: string;
  readonly sourceUrl: string;
}

import type { PhotoName } from "./photo-manifest.ts";

/*
 * Typed as the interface, not `as const`.
 *
 * With a const assertion TypeScript narrows `licenseUrl` to the two literal
 * URLs that happen to be in use today, and then proves the public-domain
 * branch in the credit line unreachable — so adding a public-domain
 * photograph later would break the build in a file nobody edited.
 */
export const PHOTO_CREDITS: Record<PhotoName, PhotoCredit> = {
  "tire-tread": {
    author: "Lee Coursey from Decatur, GA",
    license: "CC BY 2.0",
    licenseUrl: "https://creativecommons.org/licenses/by/2.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Texture_-_tire_tread_(30784753).jpg",
  },
  "tire-stack": {
    author: "Biso",
    license: "CC BY 3.0",
    licenseUrl: "https://creativecommons.org/licenses/by/3.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Truck_tires.JPG",
  },
  "depot": {
    author: "THE STEPHEN J MASON PHOTOGRAPHY COLLECTION",
    license: "CC BY-SA 2.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/2.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:AKDP_BUS_PROBOLINGGO_JAVA_INDONESIA_APRIL_2010.jpg",
  },
};
